# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Serializer
version:      0.02
version_from: lib/Class/Serializer.pm
installdirs:  site
requires:
    B::Deparse:                    0
    Data::Dumper:                  0
    File::Path:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
